# Welcome to Jekyll!
#
# Toto je soubor s hlavním nastavením. Na začátku je nastavení proměných, které
# je třeba přispůsobit si pro váš web. Později v anglicky popsané části jsou více
# technické nastavení
#

title: Piráti - Přerov # To co je napsané na tabu ve kterém je stránka.
email: prerov@pirati.cz
description: >-
  Česká pirátská strana - Přerov
# dobré keywords jsou ty co lidé piší do googlu když hledají naši stránku
keywords: přerov, piráti, česká pirátská strana, politická strana, politika, demokracie, svoboda, otevřenost, transparentnost
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://prerov.pirati.cz" # the base hostname & protocol for your site

mediaStorage: prerov

administrator:
  email: jan.suchanek@gmail.com, honza.dvorak@pirati.cz, jaromirhorky14@gmail.com

organization:
  name: Piráti - Přerov
  shortName: Piráti - Přerov
  email: prerov@pirati.cz
  phone: +420 778 522 095
  address: |
    Pepř Přerov
    Palackého 24,
    750 02, Přerov
  residenceImg: https://a.pirati.cz/prerov/img/pepr-centrum-3.jpg
  mapLink: https://www.google.com/maps/place/PEPŘ+-+Pirátské+centrum+Přerov/@49.4533437,17.4457439,17z/data=!3m1!4b1!4m5!3m4!1s0x4713af92013e7b5b:0x38dd0a27ee56101c!8m2!3d49.4533245!4d17.4478835
  redmineLink: https://redmine.pirati.cz/projects/prerov
  dataBoxId: b2i4r6j
  transparentAccount: 2100048174/2010

# Nastavení zobrazení tabulky kontaktů.
# Lze využít:
# 1) předdefinované typy (organizationEmail, organizationRedmineLink, organizationPhone, organizationTransparentAccount, organizationDataBox, piratiRootWebsite)
# 2) vlastní řádky - zde je nutné jako type dát `custom` a vyplnit `label` a `body`
contactSummaryItems:
  - type: organizationEmail
  #- type: organizationRedmineLink
  - type: organizationPhone
  - type: organizationTransparentAccount
    includeMoreLink: true
  - type: organizationDataBox
#  - type: piratiRootWebsite
#  - type: custom
    #iconClass: fa fa-envelope
    #label: Vlastní řádek tabulky
    #body: <a href="http://example.com">link</a>

calendar:
  # For nice look of the calendar, make sure you get Google Calendar API key
  # and start the app with the env var `GOOGLE_CALENDAR_APIKEY=[myapikey] bundle exec jekyll serve`.
  # For deployment, contact website administrator to set you env variable.
  title: Kalendář místního sdružení 
  id: 72ibh460q89vddgeb8p97s17q0@group.calendar.google.com
  page: https://calendar.google.com/calendar/embed?src=72ibh460q89vddgeb8p97s17q0%40group.calendar.google.com&ctz=Europe%2FPrague

facebook:
  loadSDK: true
  #vyplně adresu vaší stranky, funguje pouze na stránky nikoliv skupiny
  profilePage: https://www.facebook.com/PiratiPrerov
  profilePageName: Piráti - Přerov
  #appId: 1526197851008996

twitter:
  loadSDK: true
  profile: piratiOlomoucko

instagram:
  profilePage: https://www.instagram.com/olomouctipirati/?hl=cs

gplus:
  #profilePage: https://plus.google.com/u/0/+piratskastrana

flicker:
  #profilePage: https://www.flickr.com/photos/pirati/

forum:
  page: https://forum.pirati.cz/viewforum.php?f=666

github:
  url: https://github.com/pirati-web/prerov.pirati.cz/
  branch: master

youtube:
  channel: CeskaPiratskaStrana

#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

github_username:  pirati-web

sass:
  style: compressed
  sass_dir: _sass

theme: jekyll-theme-pirati
# Build settings
markdown: kramdown
theme: jekyll-theme-pirati
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-environment-variables
  - jekyll-redirect-from
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - TODO.txt

permalink: /aktuality/:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/

  program:
    output: true
    permalink: /program/:path/
    
  volby2020:
    output: true
    permalink: /volby-2020/:path/

  # Sole purpose is to create candidate lists in separate files.
  candidatelists:
    output: false

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "person"
      rbar:
        - profile
        - people
  -
    scope:
      path: "_program"
    values:
      layout: "program-post"
      rbar:
         - garant
         - program

emptyArray: []

assets:
  source_maps: true
  compression: true
  gzip: false
  plugins:
    css: { autoprefixer: {}}
    img:
      optim:
        jpegoptim:
          strip: all
          max_quality: 80
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
  sources:
    - vendor/bundle/ruby/2.5.0/gems/jekyll-theme-pirati-8.4.6/assets/img
    - assets/css
    - assets/fonts
    - assets/video
    - assets/img
    - _sass

styleguide_base_url: 'https://styleguide.pirati.cz/latest/'
